_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 5
                - 41
                - 53
            "2":
                - 1
                - 5
                - 41
                - 53
            "3":
                - 2
                - 16
                - 17
                - 55
                - 61
            "4": 3.10.16
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
action:
    value: train
activation:
    value: relu
adambeta:
    value: 0.98
attention_dropout:
    value: 0.2
attn_dir:
    value: ./attn/surgery_I3D_new/split_5
baloss:
    value: false
beta:
    value: 0.15
bz:
    value: 1
d_ffn_PG:
    value: 128
d_ffn_R:
    value: 64
d_model_PG:
    value: 64
d_model_R:
    value: 32
dataset:
    value: surgery_I3D_new
device:
    value: cuda:0
ffn_dropout:
    value: 0.2
gamma:
    value: 0.15
gpu:
    value: 0
input_dim:
    value: 1024
input_dropout:
    value: 0.3
l_seg:
    value: 200
lr:
    value: 0.0005
model:
    value: TUT
model_dir:
    value: ./checkpoints/surgery_I3D_new/split_5
n_heads_PG:
    value: 4
n_heads_R:
    value: 4
num_R:
    value: 3
num_classes:
    value: 12
num_epochs:
    value: 100
num_layers_PG:
    value: 5
num_layers_R:
    value: 5
num_workers:
    value: 1
pre_norm:
    value: false
results_dir:
    value: ./results/surgery_I3D_new/split_5
root_path:
    value: /mnt/hdd2/Projects_dai/Projects_dai/ASFormer/data/
rpe_share:
    value: false
rpe_use:
    value: false
split:
    value: "5"
train_ratio:
    value: 1
use_wandb:
    value: true
wandb_project:
    value: TUT-Surgery
weight_decay:
    value: 1e-05
window_size:
    value: 31
